#!/bin/bash
# Assemble tools/batch_geom.s and emit remote/BatchGeom.c with the bytes inline.
#
# The interpreter is written as assembly on purpose. Hand-encoding aarch64 is how
# you get one wrong bit and a SpringBoard that dies at a random address, and the
# device this runs on cannot be used to iterate. clang assembles it, llvm-objcopy
# extracts it, and the C file is generated rather than edited, so the two can
# never drift.
set -e
cd "$(dirname "$0")/.."

SRC=tools/batch_geom.s
TMP=$(mktemp -d -t bg.XXXXXX)
OBJ="$TMP/bg.o"
BIN="$TMP/bg.bin"

clang -target aarch64-apple-ios15.0 -c "$SRC" -o "$OBJ"
llvm-objcopy -O binary --only-section=.text "$OBJ" "$BIN"

SIZE=$(stat -c %s "$BIN")

{
  echo "// GENERATED by tools/gen_batch_geom.sh from tools/batch_geom.s. Do not edit."
  echo "//"
  echo "// $SIZE bytes of aarch64. Copied into SpringBoard with mmap(PROT_EXEC) and"
  echo "// called once per frame, so that a frame's worth of CGPath calls costs one"
  echo "// remote call instead of one per call."
  echo "//"
  echo "// Contract, from batch_geom.s: x0 points at a BatchHeader in the target's"
  echo "// address space. See tools/batch_geom.s for the layout and why the register"
  echo "// choices are what they are."
  echo ""
  echo "#include \"BatchGeom.h\""
  echo ""
  echo "const unsigned char kBatchGeomCode[] = {"
  od -An -v -tx1 "$BIN" | awk '{for (i=1;i<=NF;i++) { printf "0x%s,", $i; if (++n % 12 == 0) printf "\n" }}'
  echo ""
  echo "};"
  echo "const unsigned kBatchGeomCodeLen = $SIZE;"
} > remote/BatchGeom.c

rm -rf "$TMP"
echo "wrote remote/BatchGeom.c ($SIZE bytes of code)"
